#define GAME_RULES_BASEVALUE_LEVEL1 40
#define GAME_RULES_BASEVALUE_LEVEL2 100
#define GAME_RULES_BASEVALUE_LEVEL3 300
#define GAME_RULES_BASEVALUE_LEVEL4 1200
#define GAME_RULES_LINES_PER_LEVEL 10
#define GAME_UPDATE_RATE_BASE_MS 1000
#define GAME_UPDATE_RATE_REDUCTION_MS 90

#define BOARD_WIDTH 10
#define BOARD_HEIGHT 15

#define VIEW_BOARD_PIXEL_WIDTH 4
#define VIEW_BOARD_PIXEL_HEIGH 2

#define CTRL_QUIT 'q'
