#define RULES_BASEVALUE_LEVEL1 40
#define RULES_BASEVALUE_LEVEL2 100
#define RULES_BASEVALUE_LEVEL3 300
#define RULES_BASEVALUE_LEVEL4 1200
#define RULES_LINES_PER_LEVEL 10

#define UPDATE_RATE_BASE_MS 1000
#define UPDATE_RATE_REDUCTION_MS 90

#define BOARD_WIDTH 10
#define BOARD_HEIGHT 15

#define CTRL_QUIT 'q'

#define VIEW_LEFTSIDE_PANE_WIDTH 25
#define VIEW_BOARD_PIXEL_WIDTH 4
#define VIEW_BOARD_PIXEL_HEIGH 2