#define RULES_BASEVALUE_LEVEL1 40
#define RULES_BASEVALUE_LEVEL2 100
#define RULES_BASEVALUE_LEVEL3 300
#define RULES_BASEVALUE_LEVEL4 1200
#define RULES_LINES_PER_LEVEL 10

#define UPDATE_RATE_BASE_MS 1000
#define UPDATE_RATE_REDUCTION_MS 90

#define BOARD_WIDTH 10
#define BOARD_HEIGHT 20

#define CTRL_MOVELEFT 'a'
#define CTRL_MOVERIGHT 'd'
#define CTRL_SPEEDUP 's'
#define CTRL_ROTATE 'w'
#define CTRL_QUIT 'q'

#define VIEW_BOARD_PIXELWIDTH 2
#define VIEW_BOARD_PIXELHEIGH 1
#define VIEW_BOARD_BACKGROUND ". "
#define VIEW_BOARD_BOTTOMBORDER '='
#define VIEW_BOARD_LEFTBORDER "<!"
#define VIEW_BOARD_RIGHTBORDER "!>"
#define VIEW_LEFTSIDE_WIDTH 20
#define VIEW_TETROMINO_CELL "00"