#define RULES_BASEVALUE_LEVEL1 40
#define RULES_BASEVALUE_LEVEL2 100
#define RULES_BASEVALUE_LEVEL3 300
#define RULES_BASEVALUE_LEVEL4 1200
#define RULES_LINES_PER_LEVEL 10

#define UPDATE_RATE_BASE_MS 1000
#define UPDATE_RATE_REDUCTION_MS 90

#define BOARD_WIDTH 10
#define BOARD_HEIGHT 11

#define CTRL_MOVELEFT 'a'
#define CTRL_MOVERIGHT 'd'
#define CTRL_SPEEDUP 's'
#define CTRL_ROTATE 'w'
#define CTRL_QUIT 'q'

#define VIEW_LEFTSIDE_PANE_WIDTH 20
#define VIEW_BOARD_PIXEL_WIDTH 3
#define VIEW_BOARD_PIXEL_HEIGH 2
#define VIEW_BOARD_BORDER_THICKNESS 1
#define VIEW_BOARD_BORDER_STROKE '~'
#define VIEW_TETROMINO_STROKE '%'
#define VIEW_BOARD_BACKGROUND_STROKE ' '